version: '3.1'

services:
  mysql:
    image: mysql:5.7.31
    container_name: mysql-accessgym
    restart: unless-stopped
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pjmYFW28LuQmVXCo9tLB1"]
      interval: 5s
      timeout: 10s
      retries: 2
      start_period: 20s
    environment:
      MYSQL_ROOT_PASSWORD: jmYFW28LuQmVXCo9tLB1
      MYSQL_DATABASE: acessgym
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      #- ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
  frontend:
    build: ./frontend
    container_name: frontend-accessgym
    restart: unless-stopped
    ports:
      - 4200:4200
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4200"]
      interval: 5s
      timeout: 3s
      start_period: 25s
      retries: 2
    depends_on:
      - mysql
      - backend
    volumes:
      - frontend_node_modules:/usr/src/app/node_modules
      - ./frontend/src:/app/src
  backend:
    build: ./backend
    command: src/init_script.sh
    container_name: backend-accessgym
    restart: unless-stopped
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      start_period: 20s
      retries: 2
    devices:
      - /dev/ttyS2:/dev/ttyACM0
    depends_on:
      - mysql
    volumes:
      - backend_node_modules:/usr/src/app/node_modules
      - ./backend/src:/usr/src/app/src
      - backend_uploads:/usr/src/app/uploads
volumes:
    frontend_node_modules:
    backend_node_modules:
    backend_uploads:
    mysql-data: